# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hi, I'm Danny | Do Good, Better
email: hello@summerlin.co
description: >- # this means to ignore newlines until "baseurl:"
  Home of Salesforce Navigator, Power BI Navigator, and random stuff
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:slug
url: "https://summerlin.co" # the base hostname & protocol for your site, e.g. http://example.com
categories: ["the-prophet", "technology", "culture"]
# Build settings
remote_theme: dannysummerlin/some-style-please
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  values:
    layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
